config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resources :voters, only: [:new, :create, :update]
  get '/evaluate_movies', to: 'evaluate_movies#evaluate_movies', as: :evaluate_movies
  post '/save_evaluations', to: 'evaluate_movies#save_evaluations', as: :save_evaluations
  get '/thank_you', to: 'static#thank_you', as: :thank_you
  get '/tmdb/show/:id', to: 'tmdb#show', as: :tmbd
  get '/stats', to: 'static#stats', as: :stats
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  validate :movie_id, :voter_id, presence: true
  validate :rating, numericality: {only_integer: true, greater_than: -1, less_than: 6}
  belongs_to :voter
  belongs_to :movie
  scope :not_voted, ->{where(rating: nil)}
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validate :themoviedb, :title, presence: true
  default_scope ->{order(:created_at)}
  has_many :evaluations
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  default_scope ->{order(:created_at)}
  has_many :evaluations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/evaluate_movies_controller.rb
class EvaluateMoviesController < ApplicationController
  def evaluate_movies
    @voter = Voter.find(cookies.signed[:voter_id])
    Movie.all.each do |m|
      @voter.evaluations.new(movie_id: m.id, voter_id: @voter.id)
    end
  end

  def save_evaluations
    puts params
    params[:evaluation].each do |evaluation|
      @eval = Evaluation.new()
      @eval.voter_id = evaluation[1][:voter_id].to_i
      @eval.movie_id = evaluation[1][:movie_id].to_i
      evaluation[1][:rating] != '-1' ? @eval.rating = evaluation[1][:rating] : @eval.rating = nil
      @eval.save
    end
    cookies.delete :voter_id
    redirect_to thank_you_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index; end

  def thank_you; end

  def stats
    @voters_count=Voter.count
    @voters_finished=Evaluation.count/Movie.count
    @voters_failed=Voter.count-(Evaluation.count/Movie.count)

    @total_evals=Evaluation.count
    @avg_seen_per_session=Evaluation.where.not(rating: nil).count/(Evaluation.count/Movie.count)
    @avg_rating = 0
    Evaluation.where.not(rating: nil).each do |ev|
      @avg_rating += ev.rating
    end
    @avg_rating /= Evaluation.where.not(rating: nil).count
  end
end

app/controllers/tmdb_controller.rb
class TmdbController < ApplicationController
  layout false
  def show
    @tmdb_id = Movie.find(params[:id]).themoviedb
    @movie_params = Tmdb::Movie.detail(@tmdb_id)
    @base_url = Tmdb::Configuration.new.base_url
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def new
    @voter = Voter.new
  end

  def create
    @voter = Voter.new(voter_params)
    if @voter.save
      cookies.signed[:voter_id] = @voter.id
      redirect_to evaluate_movies_path
    else
      render :new
    end
  end

  def update
    @voter.find(params[:id])
    @voter.update(voter_params)
    redirect_to thanks_path
  end

  private

  def voter_params
    params.require(:voter).permit(:name, evaluations_attributes: [:rating])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/evaluate_movies/_js_ready.haml
:javascript
  $(".rating").rating({
    'step': 1,
    'size': 'xs',
    'starCaptions': {
        '-1': 'Not seen',
        '0': 'Very bad',
        '1': 'Bad',
        '2': 'Can be',
        '3': 'Quite fine',
        '4': 'Great movie',
        '5': 'Masterpiece'
      },
    clearCaption: "Very bad",
    });

  $(".chk-btn").bootstrapSwitch({
    'onColor': 'danger',
    'onText': 'not seen',
    'offText': 'watched'
  });

  $(".not-seen").click(function(e){
    num_id = "#rat-" + this.id.split('-')[1];
    $(num_id).rating('update', -1)
    return false;
  })

  var tour = {
      id: "hello-voter",
      steps: [
        {
          title: "Movie Title",
          content: "There are titles of movies that You can rate. Click it for more information about the movie",
          target: document.querySelector(".movie-title"),
          placement: "bottom",
          yOffset: -40
        },
        {
          title: "Current rating",
          content: "Here is your chosen rating for the movie. At the beggining all movies are set as not watched",
          target: document.querySelector(".caption"),
          placement: "bottom"
        },
        {
          title: "Zero rating",
          content: "Click here if you have seen the movie and it was very very bad",
          target: document.querySelector(".clear-rating-active"),
          placement: "right",
          yOffset: -17
        },
        {
          title: "Stars",
          content: "Click on stars to give rating from 1 to 5",
          target: document.querySelector(".rating-container"),
          placement: "bottom"
        },
        {
          title: "If mistaken",
          content: "If You made a mistake and You have not seen a movie, click here to mark it as not seen",
          target: document.querySelector(".not-seen"),
          placement: "bottom"
        }
      ]
    };

    // Start the tour!
    hopscotch.startTour(tour);

app/views/evaluate_movies/_modal.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4#myModalLabel.modal-title Modal title
      .modal-body
        \...

app/views/evaluate_movies/evaluate_movies.html.haml
.jumbotron.main-content
  %h1.main-title.center Movie list

  =form_tag save_evaluations_path do |f|

    %table.table.table-striped.table-hovered
      %thead
        %tr
          %th.m-id ID
          %th.m-title Title
          %th.m-rating Rating
      %tbody
        -@voter.evaluations.each_with_index do |eval,i|
          %tr
            %td=(i+1).to_s
            %td.movie-title=link_to eval.movie.title, tmbd_path(eval.movie_id) , id: "mid-#{eval.movie_id}", class: 'title-modal', 'data-toggle' => 'modal', 'data-target' => '#myModal', remote: true
            %td
              =link_to 'Not seen', "#", class: 'btn btn-warning btn-xs not-seen', id: "notseen-#{i}"
              =number_field_tag "evaluation[#{i}][rating]", -1, { class: 'rating', id: "rat-#{i}"}
              =hidden_field_tag "evaluation[#{i}][movie_id]", eval.movie_id
              =hidden_field_tag "evaluation[#{i}][voter_id]", eval.voter_id
              =#check_box_tag 'seen', 'not_seen', true, class: 'chk-btn', id: "chk-#{i}"
    =submit_tag 'Send votes', class: 'btn btn-success btn-lg btn-block', data: {confirm: 'Are You sure You want to submit votes?'}

=render 'modal'
=render 'js_ready'

:javascript
  $('.title-modal').bind('ajax:success', function(evt, data, status, xhr){
    $('#myModal').html(xhr.responseText);
  });

  $('.title-modal').bind("ajax:beforeSend", function(evt, xhr, settings){
    $('#myModal').html('');
  })

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rater
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .main-content
      = yield

app/views/tmdb/show.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4#myModalLabel.modal-title=@movie_params[:title]
    .modal-body
      %p.poster=image_tag(@base_url+'w154'+@movie_params[:poster_path])
      %p=@movie_params[:overview]
      Production companies:
      %ul
        -@movie_params[:production_companies].each do |p|
          %li=p[:name]
      Production countries:
      %ul
        -@movie_params[:production_countries].each do |p|
          %li=p[:name]
      Release date:
      %p=@movie_params[:release_date]
      Runtime:
      %p=@movie_params[:runtime]

app/views/voters/new.html.haml
.jumbotron.main-content
  %h1.main-title.center Please enter Your name

  =form_for @voter do |f|
    .form-group{class: "#{'has-error' if @voter.errors.any?}"}
      =f.label('Name cannot be missing and must be uniqe', class: 'control-label') if @voter.errors.any?
      =f.text_field :name, class: 'form-control'
    .form-group
      =f.submit 'Save and start voting', class: 'btn btn-lg btn-success btn-block'